name: base64 test

on:
  push:
    branches: [main]

jobs:
  base64:
    runs-on: ubuntu-latest

    steps:
      - name: base64
        run: echo -n ${{ secrets.ANDROID_RELEASE_KEY_JKS }} | base64 -d > temp.txt
